sudo: false
language: python

os:
 - linux

python:
  - "2.7"
  - "3.6"

install:
  # install library
  - pip install codecov
  - pip install .[test]

script:
  - coverage run tests

branches:
  only:
    - master

after_success:
  - codecov